[package]
name = "rofi-server"
version = "0.3.0"
authors = ["Daniel <ddl37.nz@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.25"
async-std = "1.12.0"
async-tungstenite = "0.19.0"

serde = "1.0.152"
serde_json = "1.0.91"
serde_derive = "1.0.152"

log = "0.4.17"
pretty_env_logger = "0.4.0"
